In [3]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

2.5.1
3.0.5

In [5]:
data=pd.read_csv("lab2_machines.csv")
data.head()

  machine_type  runtime_hours  temperature  vibration  pressure  needs_service
0        lathe         1837.7        60.23       1.61      3.96              0
1        lathe          560.1        90.55       3.96      3.12              1
2        press          551.5        65.58       1.29      5.04              0
3        drill          968.6        71.60       2.87      4.30              0
4        lathe         2688.5        72.06       2.30      4.68              0

In [6]:
data.shape

(300, 6)

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   machine_type   300 non-null    str
 1   runtime_hours  300 non-null    float64
 2   temperature    270 non-null    float64
 3   vibration      277 non-null    float64
 4   pressure       284 non-null    float64
 5   needs_service  300 non-null    int64
dtypes: float64(4), int64(1), str(1)
memory usage: 14.2 KB

In [9]:
data.describe()

       runtime_hours  temperature   vibration    pressure  needs_service
count     300.000000   270.000000  277.000000  284.000000     300.000000
mean     2077.605667    69.733852    2.237365    3.797711       0.206667
std      1134.521804    10.322945    1.094313    0.786678       0.405591
min        61.000000    48.750000    0.440000    1.290000       0.000000
25%      1061.650000    62.965000    1.530000    3.337500       0.000000
50%      2136.550000    66.740000    1.980000    3.890000       0.000000
75%      3072.775000    72.925000    2.430000    4.380000       0.000000
max      3992.100000   101.070000    5.950000    5.550000       1.000000

In [11]:
data.dtypes

machine_type         str
runtime_hours    float64
temperature      float64
vibration        float64
pressure         float64
needs_service      int64
dtype: object